//created on: May 19, 2016
package rules.credit;


import org.apache.camel.loanbroker.credit.CreditScore;
import org.apache.camel.loanbroker.credit.Customer;
import org.apache.camel.loanbroker.service.RFQProvider;
import java.util.List;
import function org.apache.camel.loanbroker.util.CreditScoreUtil.isCustomerOnEP;
import function org.apache.camel.loanbroker.util.CreditScoreUtil.isCustomerPR;
import function org.apache.camel.loanbroker.util.CreditScoreUtil.isCustomerCitizen;


declare CreditScore
    @role(event)
 end
 
 declare Customer
    @role(event)
 end
 
 

global RFQProvider rfqProvider;
global List<String> bankList;




/*rule " Citizen or PR and credit score <= 1 "

    when
        $creditScore : CreditScore($ssn:SSN, creditScore <= 1, (isCustomerPR($ssn) &&  isCustomerCitizen($ssn)) )       
    then
          System.out.println("Citizen or PR and credit score <= 1"); 
          System.out.println("CreditScore :::"+ $creditScore.getCreditScore()); 
          bankList.addAll(rfqProvider.getListOfBanksBasedOnCreditScore($creditScore.getCreditScore()));
end

rule " Citizen or PR and credit score between 1 and 3 " 
   
    when
        $creditScore : CreditScore($ssn:SSN,(creditScore > 1 || creditScore < 3), (isCustomerPR($ssn) &&  isCustomerCitizen($ssn)))  
    then
    
          System.out.println("Citizen or PR and credit score between 1 and 3triggered"); 
          System.out.println("CreditScore :::"+ $creditScore.getCreditScore()); 
          bankList.addAll(rfqProvider.getListOfBanksBasedOnCreditScore($creditScore.getCreditScore()));
        //retract($creditScore);

end


rule "Citizen or PR and income > 5000"   
 
    when
             
        $creditScore : CreditScore($ssn:SSN ,creditScore > 5 , (isCustomerPR($ssn) &&  isCustomerCitizen($ssn))) 
    then
         System.out.println("Citizen or PR and income > 5000"); 
         System.out.println("CreditScore :::"+ $creditScore.getCreditScore()); 
         bankList.addAll(rfqProvider.getListOfBanksBasedOnCreditScore($creditScore.getCreditScore()));

end

*/



rule "Credit Score < 5"   
 
    when
             
        $creditScore : CreditScore($ssn:SSN ,creditScore <= 5) 
    then
         System.out.println("Credit Score < 5"); 
         System.out.println("CreditScore :::"+ $creditScore.getCreditScore()); 
         bankList.addAll(rfqProvider.getListOfBanksBasedOnCreditScore($creditScore.getCreditScore()));

end



rule "Credit Score between 5 and 7"   
 
    when
             
        $creditScore : CreditScore($ssn:SSN , (creditScore > 5 && creditScore < 7)) 
    then
         System.out.println("Credit Score between 5 and 7"); 
         System.out.println("CreditScore :::"+ $creditScore.getCreditScore()); 
         bankList.addAll(rfqProvider.getListOfBanksBasedOnCreditScore($creditScore.getCreditScore()));

end



rule "Credit Score > 7"   
 
    when
             
        $creditScore : CreditScore($ssn:SSN ,creditScore > 7) 
    then
         System.out.println("Credit Score > 7"); 
         System.out.println("CreditScore :::"+ $creditScore.getCreditScore()); 
         bankList.addAll(rfqProvider.getListOfBanksBasedOnCreditScore($creditScore.getCreditScore()));

end