package rule.credit-processing



/*import org.apache.camel.loanbroker.credit.CreditScore;
import org.apache.camel.loanbroker.credit.Customer;
import function org.apache.camel.loanbroker.util.CreditScoreUtil.isCustomerPR;
import function org.apache.camel.loanbroker.util.CreditScoreUtil.isCustomerCitizen;








declare CreditScore
    @role(event)
 end
 
 declare Customer
    @role(event)
 end
 


rule "Cutomer Citizen or PR and income < 5000"

    when
        $cutomer : Customer((ssn.startWith("C")|| (ssn.startWith("P")) && amount > 5000)       
    then
        insert(new CreditScore(5,ssn));
end

rule "Cutomer Citizen or PR and income between 5000 and 7000"    
    when
        $cutomer : Customer((isCustomerPR(ssn) || isCustomerCitizen(ssn)) && amount > 5000 && amount < 7000)    
    then
         insert(new CreditScore(6,ssn));

end


rule "Cutomer Citizen or PR and income > 7000"    
    when
        $cutomer : Customer((isCustomerPR(ssn) || isCustomerCitizen(ssn)) && amount > 7000)    
    then
         insert(new CreditScore(8,ssn));

end*/
